// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJkyPsvlW12lFtoEUtwP7PvELIo6qbWbQ',
    appId: '1:748680012359:android:a240476e10c41747880762',
    messagingSenderId: '748680012359',
    projectId: 'snack-shop-67138',
    databaseURL: 'https://snack-shop-67138-default-rtdb.firebaseio.com',
    storageBucket: 'snack-shop-67138.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD193tgeHjzLYsgHYhy0Km6HsODyb9cYUE',
    appId: '1:748680012359:ios:b75df0524663737c880762',
    messagingSenderId: '748680012359',
    projectId: 'snack-shop-67138',
    databaseURL: 'https://snack-shop-67138-default-rtdb.firebaseio.com',
    storageBucket: 'snack-shop-67138.appspot.com',
    iosBundleId: 'com.example.snackShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD193tgeHjzLYsgHYhy0Km6HsODyb9cYUE',
    appId: '1:748680012359:ios:7dc4b8b538e40c8c880762',
    messagingSenderId: '748680012359',
    projectId: 'snack-shop-67138',
    databaseURL: 'https://snack-shop-67138-default-rtdb.firebaseio.com',
    storageBucket: 'snack-shop-67138.appspot.com',
    iosBundleId: 'com.example.snackShop.RunnerTests',
  );
}
